spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 1000
logging:
  level:
    com.lhz.mapper: off
server:
  port: 9090